language: ruby
rvm:
  - 2.2
cache: bundler
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-favicon # --check-html add back in once bug fixed
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
